---
title: "Tour de France"
author: "zahlooh"
date: "4/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(ggpattern)
library(ggimage)
library(countrycode)
library(EBImage)
library(gganimate)
theme_set(theme_light())
```

# Get Data
```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 15)

tdf.stg.typ <- data.frame(matrix(c("flat cobblestone stage", "flat",
                            "flat stage", "flat",
                            "half stage", "other",
                            "high mountain stage", "mountain", 
                            "hilly stage", "hilly",
                            "individual time trial", "time trial",
                            "intermediate stage", "other",
                            "medium mountain stage", "mountain",
                            "mountain stage", "mountain",
                            "mountain time trial", "time trial",
                            "plain stage", "flat",
                            "plain stage with cobblestones", "flat",
                            "stage with mountain", "mountain",
                            "stage with mountain(s)", "mountain",
                            "team time trial", "time trial",
                            "transition stage", "other"), ncol = 2, byrow = TRUE))
names(tdf.stg.typ) <- c("Type", "type2")

# detailed results by stage
tdf.dtl <- tuesdata$stage_data %>%
  extract(stage_results_id, into = "stage_id", "stage-(.*)", remove = TRUE) %>%
  mutate(stage_id = as.numeric(stage_id),
         rank = as.numeric(rank)) %>%
  separate(rider, into = c("last_name", "first_name"), sep = " ") %>%
  relocate(stage_id, .after = year)

tdf.win <- tuesdata$tdf_winners %>% # final results
  mutate(year = year(start_date)) %>%
  separate(winner_name, into = c("first_name", "last_name", sep = " "))

tdf.stg <- tuesdata$tdf_stages %>% # stage details
  mutate(year = year(Date),
         stage_id = as.numeric(Stage),
         Type = str_to_lower(Type)) %>%
  left_join(tdf.stg.typ)

```

# Who had the highest range of places over stages
```{r}
tiff("TDF_num_of_racers_drop.tiff", units="in", res=300, width=8, height=4.5)
tdf.dtl %>%
  count(year, stage_id, name = "racers_n") %>%
  group_by(year) %>%
  mutate(racers_rng = max(racers_n) - min(racers_n),
         label = paste0(year, ": ", racers_rng)) %>%
  ungroup() %>%
  filter(year >= 2000) %>%
  ggplot(aes(x = stage_id, y = racers_n, col = factor(year))) +
    geom_line(size = 1.5) +
    gghighlight::gghighlight(max(racers_rng), max_highlight = 5L, label_key = label) +
    labs(x = "Stage", y = "Number of racers", title = "Which years seen the highest drop in number of racers over stages?", subtitle = "Races not earlier than 2000")
```

# Races with the most race lead changes
```{r}
library(png)
mypng <- readPNG('120px-Olympic_pictogram_Cycling.png')

tdf.dtl.mean_rank <- tdf.dtl %>%
  inner_join(tdf.stg %>% select(year, stage_id, type2), by = c("year", "stage_id")) %>%
  inner_join(tdf.win %>% select(year, first_name, last_name), by = c("year", "first_name", "last_name")) %>%
  filter(year >= 2000) %>%
  group_by(type2) %>% summarize(mean_rank = mean(rank)) %>% ungroup()

tdf.dtl %>%
  inner_join(tdf.stg %>% select(year, stage_id, type2), by = c("year", "stage_id")) %>%
  inner_join(tdf.win %>% select(year, first_name, last_name), by = c("year", "first_name", "last_name")) %>%
  inner_join(tdf.dtl.mean_rank, by = "type2") %>%
  filter(year >= 2000) %>%
  add_count(type2, name = "stg_type_num") %>% mutate(type = fct_reorder(type2, stg_type_num)) %>%
  mutate(winner = fct_reorder(paste0(first_name, " ", last_name, ", ", year), year)) %>%
  ggplot(aes(x = type, y = rank, col = type)) +
    geom_boxplot(outlier.alpha = 0) +
    geom_jitter(height = .02, alpha = .5) +
    #geom_image(aes(image = rep(mypng, times = 371), x = type, y = mean_rank + 100), inherit.aes = FALSE) +
    geom_text(aes(label = "\uD83D\uDEB2", x = type, y = mean_rank + 75, angle = 0, vjust = 0), size = 20) +
    #scale_y_reverse() +
    coord_flip() +
    labs(title = "Tour de France winners are experts in Mountain and Time Trial stages",
         subtitle = "stages sorted by frequency",
         y = "Winner's stage rank",
         x = "Stage type") +
    theme(legend.position = "none")
ggsave("TDF_winners_stage_type_rank.tiff", units="in", dpi=300, width=8, height=4.5)

```

# Animate that
```{r}
# tdf.dtl %>%
#   inner_join(tdf.stg %>% select(year, stage_id, type2), by = c("year", "stage_id")) %>%
#   inner_join(tdf.win %>% select(year, first_name, last_name), by = c("year", "first_name", "last_name")) %>%
#   add_count(type2, name = "stg_type_num") %>% mutate(type = fct_reorder(type2, stg_type_num)) %>%
#   group_by(year, first_name, last_name, type2) %>% summarize(mean_stg_rank = mean(rank)) %>% ungroup() %>%
#   ggplot(aes(x = type2, y = mean_stg_rank)) +
#     geom_col() +
#     coord_flip() +
#     transition_time(year) +
#     labs(title = "Year: { frame_time }",
#          x = "Winner's stage rank",
#          y = "Stage type")
```


```{r}
tdf.stg
```


# Trying to use ggpattern - didn't work
```{r}
# flags <- paste0(getwd(), "/", list.files(path = "flags", pattern = "\\.png$", full.names = TRUE)) %>% unlist()
# 
# tdf.win.flags <- tdf.win %>% 
#   add_count(winner_name, name = "person_win_n") %>%
#   add_count(birth_country, name = "country_win_n") %>%
#   mutate(winner_name = fct_reorder(winner_name, person_win_n),
#          nationality_cd = countrycode(nationality, origin = 'country.name', destination = 'iso2c') %>% str_to_lower(),
#          flag_path = paste0(getwd(), "/flags/", nationality_cd, ".png"),
#          nationality = fct_lump_n(nationality, 10, w = country_win_n))
# 
# flags <- tdf.win.flags %>%
#   filter(person_win_n > 2) %>%
#   arrange(desc(person_win_n)) %>%
#   select(winner_name, flag_path) %>%
#   unique() %>%
#   select(flag_path)
# 
# tdf.win.flags %>%
#   filter(person_win_n > 2) %>%
#   ggplot(aes(x = winner_name, y = person_win_n)) +
#     geom_col_pattern(aes(pattern_filename = flag_path),
#                       pattern         = 'image',
#                       pattern_type    = 'none',
#                       fill            = 'grey80',
#                       colour          = 'black',
#                       pattern_scale   = -2,
#                       pattern_filter  = 'point',
#                       pattern_gravity = 'east') +
#     scale_pattern_filename_discrete(choices = flags) +
#     coord_flip() +
#     scale_pattern_discrete(guide = guide_legend(nrow = 1)) +
#     theme(legend.position = "none")
```

